[package]
name = "rustscrape"
version = "0.1.0"
edition = "2024"

[dependencies]
headless_chrome = "1.0.17"
url = "2.5.4"
reqwest = { version = "0.12.18", features = ["json", "blocking", "brotli", "gzip", "http2", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
pdf-extract = "0.7"
