#!/usr/bin/env node

import { getWikipediaInfo } from "./wiki.js";
import slugify from "slugify";

export const getKey = name => slugify(name).toLowerCase();

const pages = [
    ["Daily Express", "https://en.wikipedia.org/wiki/Daily_Express"],
    ["Sunday Express", "https://en.wikipedia.org/wiki/Sunday_Express"],
    ["Daily Mirror", "https://en.wikipedia.org/wiki/Daily_Mirror"],
    ["Sunday Mirror", "https://en.wikipedia.org/wiki/Sunday_Mirror"],
    ["Daily Record", "https://en.wikipedia.org/wiki/Daily_Record_(Scotland)"],
    ["Sunday Mail", "https://en.wikipedia.org/wiki/Sunday_Mail_(Scotland)"],
    ["Daily Star", "https://en.wikipedia.org/wiki/Daily_Star_(United_Kingdom)"],
    ["Daily Star Sunday", "https://en.wikipedia.org/wiki/Daily_Star_Sunday"],
    ["Irish Daily Mirror", "https://en.wikipedia.org/wiki/Daily_Mirror"],
    ["Irish Daily Star", "https://en.wikipedia.org/wiki/Irish_Daily_Star"],
    ["The Mirror US", "https://en.wikipedia.org/wiki/Daily_Mirror"],
    ["Sunday People", "https://en.wikipedia.org/wiki/Sunday_People"],
    ["Western Mail", "https://en.wikipedia.org/wiki/Western_Mail_(Wales)"],
    ["Wales on Sunday", "https://en.wikipedia.org/wiki/Western_Mail_(Wales)"],
    ["Derby Telegraph", "https://en.wikipedia.org/wiki/Derby_Telegraph"],
    ["Hinckley Times", "https://en.wikipedia.org/wiki/Hinckley_Times"],
    ["Leicester Mercury", "https://en.wikipedia.org/wiki/Leicester_Mercury"],
    ["Lincolnshire Echo", "https://en.wikipedia.org/wiki/Lincolnshire_Echo"],
    ["Loughborough Echo", "https://en.wikipedia.org/wiki/Loughborough_Echo"],
    ["Nottingham Post", "https://en.wikipedia.org/wiki/Nottingham_Post"],
    ["Retford Times", "https://en.wikipedia.org/wiki/Retford_Times"],
    ["Glossop Advertiser", "https://en.wikipedia.org/wiki/Glossop_Advertiser"],
    ["Tameside Advertiser", "https://en.wikipedia.org/wiki/Tameside_Advertiser"],
    ["The Wharf", "https://en.wikipedia.org/wiki/The_Wharf_(newspaper)"],
    ["Chronicle Extra", "https://en.wikipedia.org/wiki/Chronicle_Extra"],
    ["Evening Chronicle", "https://en.wikipedia.org/wiki/Evening_Chronicle"],
    ["The Journal", "https://en.wikipedia.org/wiki/The_Journal_(Newcastle_upon_Tyne_newspaper)"],
    ["Sunday Sun", "https://en.wikipedia.org/wiki/Sunday_Sun"],
    ["Accrington Observer", "https://en.wikipedia.org/wiki/Accrington_Observer"],
    ["Chester Chronicle", "https://en.wikipedia.org/wiki/Chester_Chronicle"],
    ["Crewe Chronicle", "https://en.wikipedia.org/wiki/Crewe_Chronicle"],
    ["Liverpool Echo", "https://en.wikipedia.org/wiki/Liverpool_Echo"],
    ["Manchester Evening News", "https://en.wikipedia.org/wiki/Manchester_Evening_News"],
    ["Manchester Metro News", "https://en.wikipedia.org/wiki/Manchester_Metro_News"],
    ["Oldham Advertiser", "https://en.wikipedia.org/wiki/Oldham_Advertiser"],
    ["Rochdale Observer", "https://en.wikipedia.org/wiki/Rochdale_Observer"],
    ["Rossendale Free Press", "https://en.wikipedia.org/wiki/Rossendale_Free_Press"],
    ["Salford Advertiser", "https://en.wikipedia.org/wiki/Salford_Advertiser"],
    ["South Manchester Reporter", "https://en.wikipedia.org/wiki/South_Manchester_Reporter"],
    ["Southport Visiter", "https://en.wikipedia.org/wiki/Southport_Visiter"],
    ["Stockport Express", "https://en.wikipedia.org/wiki/Stockport_Express"],
    ["Macclesfield Express", "https://en.wikipedia.org/wiki/Macclesfield_Express"],
    ["The Sentinel (Staffordshire)", "https://en.wikipedia.org/wiki/The_Sentinel_(Staffordshire)"],
    ["Tameside Advertiser", "https://en.wikipedia.org/wiki/Tameside_Advertiser"],
    ["Glossop Advertiser", "https://en.wikipedia.org/wiki/Glossop_Advertiser"],
    ["Airdrie and Coatbridge Advertiser", "https://en.wikipedia.org/wiki/Airdrie_and_Coatbridge_Advertiser"],
    ["Ayrshire Post", "https://en.wikipedia.org/wiki/Ayrshire_Post"],
    ["Blairgowrie Advertiser", "https://en.wikipedia.org/wiki/Blairgowrie_Advertiser"],
    ["Dumfries & Galloway Standard", "https://en.wikipedia.org/wiki/Dumfries_%26_Galloway_Standard"],
    ["East Kilbride News", "https://en.wikipedia.org/wiki/East_Kilbride_News"],
    ["Hamilton Advertiser", "https://en.wikipedia.org/wiki/Hamilton_Advertiser"],
    ["Kilmarnock Standard", "https://en.wikipedia.org/wiki/Kilmarnock_Standard"],
    ["Paisley Daily Express", "https://en.wikipedia.org/wiki/Paisley_Daily_Express"],
    ["Perthshire Advertiser", "https://en.wikipedia.org/wiki/Perthshire_Advertiser"],
    ["Rutherglen Reformer", "https://en.wikipedia.org/wiki/Rutherglen_Reformer"],
    ["Wishaw Press", "https://en.wikipedia.org/wiki/Wishaw_Press"],
    ["Staines Informer", "https://en.wikipedia.org/wiki/Staines_Informer"],
    ["Surrey Advertiser", "https://en.wikipedia.org/wiki/Surrey_Advertiser"],
    ["Bath Chronicle", "https://en.wikipedia.org/wiki/Bath_Chronicle"],
    ["Bristol Post", "https://en.wikipedia.org/wiki/Bristol_Post"],
    ["Cornish Guardian", "https://en.wikipedia.org/wiki/Cornish_Guardian"],
    ["The Cornishman", "https://en.wikipedia.org/wiki/The_Cornishman_(newspaper)"],
    ["Express & Echo", "https://en.wikipedia.org/wiki/Express_%26_Echo"],
    ["Gloucester Citizen", "https://en.wikipedia.org/wiki/Gloucester_Citizen"],
    ["Gloucestershire Echo", "https://en.wikipedia.org/wiki/Gloucestershire_Echo"],
    ["The Herald", "https://en.wikipedia.org/wiki/The_Herald_(Plymouth)"],
    ["Mid Devon Gazette", "https://en.wikipedia.org/wiki/Mid_Devon_Gazette"],
    ["North Devon Journal", "https://en.wikipedia.org/wiki/North_Devon_Journal"],
    ["The West Briton", "https://en.wikipedia.org/wiki/The_West_Briton"],
    ["Western Morning News", "https://en.wikipedia.org/wiki/Western_Morning_News"],
    ["Daily Post", "https://en.wikipedia.org/wiki/Daily_Post_(North_Wales)"],
    ["South Wales Echo", "https://en.wikipedia.org/wiki/South_Wales_Echo"],
    ["South Wales Evening Post", "https://en.wikipedia.org/wiki/South_Wales_Evening_Post"],
    ["Birmingham Post", "https://en.wikipedia.org/wiki/Birmingham_Post"],
    ["Birmingham Mail", "https://en.wikipedia.org/wiki/Birmingham_Mail"],
    ["Sunday Mercury", "https://en.wikipedia.org/wiki/Sunday_Mercury"],
    ["Coventry Telegraph", "https://en.wikipedia.org/wiki/Coventry_Telegraph"],
    ["Grimsby Telegraph", "https://en.wikipedia.org/wiki/Grimsby_Telegraph"],
    ["Huddersfield Daily Examiner", "https://en.wikipedia.org/wiki/Huddersfield_Daily_Examiner"],
    ["Hull Daily Mail", "https://en.wikipedia.org/wiki/Hull_Daily_Mail"],
    ["Scunthorpe Telegraph", "https://en.wikipedia.org/wiki/Scunthorpe_Telegraph"],
    ["Bristol Live", "https://en.wikipedia.org/wiki/Bristol_Live"],
    ["Buzz.ie", "https://en.wikipedia.org/wiki/Buzz.ie"],
    ["Cheshire Live", "https://en.wikipedia.org/wiki/Cheshire_Live"],
    ["Cornwall Live", "https://en.wikipedia.org/wiki/Cornwall_Live"],
    ["Devon Live", "https://en.wikipedia.org/wiki/Express_%26_Echo"],
    ["Yorkshire Live", "https://en.wikipedia.org/wiki/Yorkshire_Live"],
    ["Hull Live", "https://en.wikipedia.org/wiki/Hull_Live"],
    ["Leicestershire Live", "https://en.wikipedia.org/wiki/Leicestershire_Live"],
    ["Lincolnshire Live", "https://en.wikipedia.org/wiki/Lincolnshire_Live"],
    ["MyLondon", "https://en.wikipedia.org/wiki/MyLondon"],
    ["Plymouth Live", "https://en.wikipedia.org/wiki/Plymouth_Live"],
    ["Somerset Live", "https://en.wikipedia.org/wiki/Somerset_Live"],
    ["Surrey Live", "https://en.wikipedia.org/wiki/Surrey_Live"],
    ["Teesside Live", "https://en.wikipedia.org/wiki/Teesside_Live"],
    ["WalesOnline", "https://en.wikipedia.org/wiki/Media_Wales#WalesOnline"],
    ["Buckinghamshire Examiner", "https://en.wikipedia.org/wiki/Buckinghamshire_Examiner"],
    ["Reading Post", "https://en.wikipedia.org/wiki/Reading_Post"],
    ["Neath Guardian", "https://en.wikipedia.org/wiki/Neath_Guardian"],
];

const entries = {};

for( const [name, url] of pages ) {
    const entry = {
        "names": [
            name,
        ],
        "comment": "",
        "sources": {},
        "sourceNotes": {},
        "tags": [
            "news"
        ],
        "score": 24,
        "ownedBy": [
            "reach"
        ],
        "updatedAt": "2026-01-03T06:28:22.531Z",
        ...(await getWikipediaInfo(name, url)),
    };
    entries[getKey(name)] = entry;
}

console.log(JSON.stringify(entries));

